/* Generated by Cython 3.2.4 */

#ifndef __PYX_HAVE__nonaga_constants
#define __PYX_HAVE__nonaga_constants

#include "Python.h"

#ifndef __PYX_HAVE_API__nonaga_constants

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int __pyx_v_16nonaga_constants_RED;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_BLACK;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_PIECE_TO_MOVE;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_TILE_TO_MOVE;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_AI_PARAM;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_HEX_SIZE;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_HEX_COLOR;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_HEX_MOVE_COLOR;
__PYX_EXTERN_C double __pyx_v_16nonaga_constants_CIRCLE_SIZE;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_RED_PIECE_COLOR;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_RED_PIECE_MOVE_COLOR;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_BLACK_PIECE_COLOR;
__PYX_EXTERN_C PyObject *__pyx_v_16nonaga_constants_BLACK_PIECE_MOVE_COLOR;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_SCREEN_WIDTH;
__PYX_EXTERN_C int __pyx_v_16nonaga_constants_SCREEN_HEIGHT;

#endif /* !__PYX_HAVE_API__nonaga_constants */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("nonaga_constants", PyInit_nonaga_constants) instead of calling PyInit_nonaga_constants directly from Python 3.5 */
PyMODINIT_FUNC PyInit_nonaga_constants(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"nonaga_constants\", PyInit_nonaga_constants) instead of calling PyInit_nonaga_constants directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"nonaga_constants\", PyInit_nonaga_constants) instead of calling PyInit_nonaga_constants directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"nonaga_constants\", PyInit_nonaga_constants) instead of calling PyInit_nonaga_constants directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_nonaga_constants_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_nonaga_constants() __PYX_WARN_IF_PyInit_nonaga_constants_INIT_CALLED(PyInit_nonaga_constants())
#endif

#endif /* !__PYX_HAVE__nonaga_constants */
